/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateProjectRequest } from '../model/models';
import { CreateProjectResponse } from '../model/models';
import { GetAllProjectsResponse } from '../model/models';
import { GetProjectByIdResponse } from '../model/models';
import { UpdateProjectRequest } from '../model/models';
import { UpdateProjectResponse } from '../model/models';
import { UpdateUserById400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddProjectRequestParams {
    createProjectRequest: CreateProjectRequest;
}

export interface DeleteProjectByIdRequestParams {
    id: number;
}

export interface GetProjectByIdRequestParams {
    id: number;
}

export interface UpdateProjectByIdRequestParams {
    id: number;
    updateProjectRequest: UpdateProjectRequest;
}


export interface ProjectsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    addProject(requestParameters: AddProjectRequestParams, extraHttpRequestParams?: any): Observable<CreateProjectResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteProjectById(requestParameters: DeleteProjectByIdRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllProjects(extraHttpRequestParams?: any): Observable<Array<GetAllProjectsResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getProjectById(requestParameters: GetProjectByIdRequestParams, extraHttpRequestParams?: any): Observable<GetProjectByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateProjectById(requestParameters: UpdateProjectByIdRequestParams, extraHttpRequestParams?: any): Observable<UpdateProjectResponse>;

}
